name: recipe_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13
  image_picker: ^1.0.7
  numberpicker: ^2.1.2
  provider: ^6.1.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/launcher_icons/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher_icons/ic_launcher.png"
  adaptive_icon_background: "assets/launcher_icons/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/launcher_icons/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/launcher_icons/ic_launcher_monochrome.png"
  min_sdk_android: 21 

flutter_native_splash:
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#3F51B5"
  image: "assets/launcher_icons/ic_launcher_foreground.png"
  android_12:
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: "assets/launcher_icons/ic_launcher_foreground.png"
    color: "#3F51B5"
